CMS = {};
CMS.menu = {
    "admin":"CMS회원관리",
    "adminmenu":"CMS회원권한",
    "advertise":"광고관리",
    "advertiselog":"통계관리",
    "advertiser":"광고주관리",
    "representative":"랩사관리",
    "banner":"배너관리",
    "user":"회원관리",
    "board":"게시판관리",
    "inquire":"고객문의관리",
    "card":"카드관리",
    "bincode":"BINCODE관리",
    "savelog":"적립로그관리",
    "uselog":"캐시백로그관리",
    "systemlog":"CMS로그관리",
    "cardsbwlog":"공항철도카드저장로그관리",
    "taglog":"공항철도카드태킹로그관리",
    "version":"앱버젼정보관리",
    "station":"지하철역정보관리",
    "area":"지역정보관리",
    "event":"이벤트관리",
    "content":"컨텐츠관리",
    "channel":"채널관리",
    "movie":"동영상관리",
    "push":"푸시관리",
    "eventlog":"이벤트적립로그관리",
    "box":"박스관리",
    "boxmember":"박스회원관리",
    "boxmessage":"박스메시지관리",
    "boxsavelog":"박스적립로그관리",
    "boxuselog":"박스혜택로그관리",
    "boxhistory":"박스히스토리"
};
CMS.cdn = "http://order.favinet.co.kr";
CMS.was = "http://order.favinet.co.kr"